### PR TITLE
Footer fixed

### PR DESCRIPTION
**Pull request by therahulchaurasia**
My PR closes the issue #31 
Hey, I worked on fixing the error and styling the footer as mentioned in the issue.
I am attaching screenshots for both. You can check them and let me know if you need some other changes.
The error with the old copyright footer has been fixed.
image

The footer now appears below the content.
image

### CODE REVIEW

**Comment by therahulchaurasia** [comment]
I cannot understand the issue with restyled. It says the check has failed but when you open the details it shows success.
Please merge my pr with the label hacktoberfest-accepted if everything seems fine to you.
Let me know if you need some changes.

**Review by devjainofficial — APPROVED** [review]

**Comment by devjainofficial** [comment]
image
After merging your pull request still has an icon issue. I you want to continue this progress, create one more pull request with icon correction..

**Comment by therahulchaurasia** [comment]
Can you attach the screenshot of the console so I can view the error? 
As soon as you mentioned the above issue I synced the fork with your repository and everything works fine on the dev server.
image

**Comment by devjainofficial** [comment]
Issue is resolved. Thanks for your support.

**Comment by therahulchaurasia** [comment]
Welcome, and I enjoyed working on your repo. 🚀

**Pull request merged**
