### PR TITLE
added responsive and highly UI based decorative footer

### PR DESCRIPTION
**Pull request by BkPankaj**
Fixes: #20 

Desktop Version:
image

Mobile Version:
image

In the social media, you can put your respective ID's, as I did not have any ID, so I inserted the home page of responsive social media.

### CODE REVIEW

**Comment by BkPankaj** [comment]
I also forgot to mention there is wave animation in whole footer and hover-moving animation on social media links

**Review by devjainofficial — APPROVED** [review]

**Review by devjainofficial — APPROVED** [review]

**Comment by devjainofficial** [comment]
Looking really awesome. I am merging your pull request.
Thanks for your Contribution.

**Comment by devjainofficial** [comment]
Hey, @BkPankaj  there is some issue in merging your request is my repo. Put one more pul request of your footer section

**Comment by BkPankaj** [comment]
Okay @devjainofficial , I will make one more pull request

**Pull request merged**
