### PR TITLE
aqi is visible now

### PR DESCRIPTION
**Pull request by LalitDeore**
aqi

Aqi is visible now. Issue was that aqi was being updated before asynchronous request made.

### CODE REVIEW

**Comment by devjainofficial** [comment]
It shows 390 for all the cities.

**Comment by LalitDeore** [comment]
airquality

I have seen response of an air quality object, but there is no data on air quality from the API. That's why there is NaN while getting that data dynamicaly from the API.

**Comment by LalitDeore** [comment]
Hey @devjainofficial  Can you merge this repo if possible? could help me with the hacktoberfest.

**Comment by devjainofficial** [comment]
Send me the screenshot of the whole running website

**Comment by devjainofficial** [comment]
Actually, while I am running your code some of the elements got misplaced. check out those fix them, then I will merge your request

**Comment by LalitDeore** [comment]
Hey @devjainofficial  i have commit changes a
aqi-updated
nd fix element misplace code.

**Comment by devjainofficial** [comment]
Sync your forked repo, you are One merge behind

**Comment by devjainofficial** [comment]
Do one more thing your code is very unreadable. Make sure to use linting

**Comment by LalitDeore** [comment]
check my latest commit I have added same code as yours on your github repo. I have comment one line which changes the dynamic updation of the aqi.

**Review by devjainofficial — APPROVED** [review]
Looking fine

**Comment by LalitDeore** [comment]
Thank you @devjainofficial you can close this pr and issue.

**Comment by devjainofficial** [comment]
Please sync your repo

**Comment by LalitDeore** [comment]
Just sync my repo

**Pull request merged**
