### PR TITLE
Dark mode button added

### PR DESCRIPTION
**Pull request by AniketNS**

### CODE REVIEW

**Comment by devjainofficial** [comment]
Please share the screenshot of both version dark and light

**Comment by devjainofficial** [comment]
I want the toggle button like this.
image

And make sure all the text should be visible and convert all the section into darkmode of the website.
image

**Comment by AniketNS** [comment]
Sure @devjainofficial, I'll work on it.

**Comment by devjainofficial** [comment]
Sorry, this one is not fulfilling what I wanted. If you want to still work on this issue, ask to reassign in new issue I opened, for I am closing this pull request. Thank you for contributing.

**Pull request closed without merging**
