### PR TITLE
Add air_quality feature from weather api

### LINKED ISSUE #17: Add more features in the application using weather api
Share the screenshot of the working website.

### PR DESCRIPTION
**Pull request by GriffinAnnshual**
Added air_quality feature from weather api fixes #17

### CODE REVIEW

**Comment by GriffinAnnshual** [comment]
Did the fixes bro. I works well now. Thank you!

**Comment by devjainofficial** [comment]
image
Fix this, and maintain the space between text and corner of box

**Comment by devjainofficial** [comment]
or instead of good, healthy..... use percentage for more impact.

**Comment by GriffinAnnshual** [comment]
Okay let me do the fixes

**Comment by devjainofficial** [comment]
Sorry, this one is not fulfilling what I wanted. If you want to still work on this issue, ask to reassign in new issue I opened, for I am closing this pull request. Thank you for contributing.

**Comment by GriffinAnnshual** [comment]
@devjainofficial Can you reassign this issue as a new one please?

**Comment by devjainofficial** [comment]
Yeah Sure. 
Please make sure the feature you will add, would not already on the website.

**Pull request closed without merging**
